I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
  File "renpy/gl2/gl2draw.pyx", line 369, in renpy.gl2.gl2draw.GL2Draw.init
  File "renpy/gl2/gl2draw.pyx", line 190, in renpy.gl2.gl2draw.GL2Draw.select_physical_size
  File "src/pygame_sdl2/display.pyx", line 93, in pygame_sdl2.display.init
pygame_sdl2.error.error: No available video device

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "renpy/bootstrap.py", line 376, in bootstrap
    renpy.main.main()
    ~~~~~~~~~~~~~~~^^
  File "renpy/main.py", line 529, in main
    renpy.game.script.report_duplicate_labels()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "renpy/script.py", line 1222, in report_duplicate_labels
    if renpy.parser.report_parse_errors():
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^ 
  File "renpy/parser.py", line 1794, in report_parse_errors
    renpy.display.error.report_parse_errors(screen_parse_errors, error_fn)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/display/error.py", line 181, in report_parse_errors
    init_display()
    ~~~~~~~~~~~~^^
  File "renpy/display/error.py", line 70, in init_display
    renpy.game.interface.start()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "renpy/display/core.py", line 1033, in start
    self.set_mode()
    ~~~~~~~~~~~~~^^
  File "renpy/display/core.py", line 1355, in set_mode
    if draw.init(virtual_size):
       ~~~~~~~~~^^^^^^^^^^^^^^ 
  File "renpy/gl2/gl2draw.pyx", line 369, in renpy.gl2.gl2draw.GL2Draw.init
  File "renpy/gl2/gl2draw.pyx", line 190, in renpy.gl2.gl2draw.GL2Draw.select_physical_size
  File "renpy/display/__init__.py", line 54, in get_info
    pygame.display.init()
    ~~~~~~~~~~~~~~~~~~~^^
  File "src/pygame_sdl2/display.pyx", line 93, in pygame_sdl2.display.init
pygame_sdl2.error.error: No available video device

Linux-6.8.0-78-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.4.1.25072401
 
Sat Aug 30 17:28:41 2025
